[package]
name = "vcl-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goblin = "0.6.1"
# dlopen = "0.1.8"
libc = "0.2.140"
libloading = "0.7.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# varnish-sys = { path = "/home/martin/varnish-rs/varnish-sys", version = "0.0.16" }
varnish-sys = "0.0.16"
chumsky = "0.8.0"
env_logger = "0.9.0"
ropey = "1.5.0"
tokio = { version = "1.17.0", features = ["full"] }
tower-lsp = { version = "0.19.0", features = ["proposed"]}
dashmap = "5.1.0"
log = "0.4.14"
im-rc = "15.0.0"
# pest = "2.5.6"
# pest_derive = "2.5.6"
tree-sitter = "0.20.9"
xi-rope = "0.3.0"
async-std = "1.12.0"

[build-dependencies]
cc = "1.0"
# pkg-config = "0.3.22"
# bindgen = "0.64.0"
