name: CI

on:
  pull_request:
  push:
    branches: [main, gh-actions]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-ci-${{ hashFiles('**/Cargo.lock') }}

      - name: Generate tree-sitter-vcl
        working-directory: ./vendor/tree-sitter-vcl
        run: |
          npm ci
          npx tree-sitter generate

      - name: Generate tree-sitter-vtc
        working-directory: ./vendor/tree-sitter-vtc
        run: |
          npm ci
          npx tree-sitter generate

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: clippy

      - name: Test
        run: cargo test

      - name: Clippy
        run: cargo clippy
